In [10]:
# 1 часть (решение задания)

import numpy as np

X = np.array([[1, 2], [4, 5]])

answer = X - (10 * 1/(X + 1))
answer

array([[-4.        , -1.33333333],
       [ 2.        ,  3.33333333]])

In [2]:
# 2 часть

import torch

x = torch.tensor(
    [[1., 2., 3., 4.],
     [5., 6., 7., 8.],
     [9., 10., 11., 12.]], requires_grad=True)
#######
#device = torch.device('cuda:0' 
#                      if torch.cuda.is_available() 
#                      else 'cpu')
#x = x.to(device)
#######

function = 10 * (x ** 2).sum()

function.backward()

print(x.grad, '<- gradient') # результат градиента в атрибуте .grad

tensor([[ 20.,  40.,  60.,  80.],
        [100., 120., 140., 160.],
        [180., 200., 220., 240.]]) <- gradient


In [2]:
# Задание 2 чатсть

import torch

w = torch.tensor([[5.,10.],[1.,2.]], requires_grad=True) # requires_grad - тензор не константа, а переменная

function =  torch.log(torch.log(w + 7)).prod()# prod() это умножение 
function.backward()

print(w.grad) # Код для самопроверки

tensor([[0.0201, 0.0109],
        [0.0449, 0.0351]])


In [1]:
import torch

x = torch.tensor(
    [[1., 2., 3., 4.],
     [5., 6., 7., 8.],
     [9., 10., 11., 12.]], requires_grad=True)
#######
#device = torch.device('cuda:0' 
#                      if torch.cuda.is_available() 
#                      else 'cpu')
#x = x.to(device)
#######

function = 10 * (x ** 2).sum()

function.backward() # порядок вычисления

x.data = 0.001 * x.grad # .data, потому что Реквайрс Град - Фолз

x.grad.zero_() # обнуляем градиент, чтобы не суммировался

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [2]:
# Задание 2 части
import torch

w = torch.tensor([[5., 10.], [1., 2.]], requires_grad=True)
alpha = 0.001

for _ in range(500):
    # critical: calculate the function inside the loop
    function = (w + 7).log().log().prod()
    function.backward()
    w.data -= alpha * w.grad # put code here
    w.grad.zero_()
    # something is missing

print(w) # Код для самопроверки, не забудьте закомментировать перед

tensor([[4.9900, 9.9948],
        [0.9775, 1.9825]], requires_grad=True)


In [3]:
# Семинар 2
import torch

x = torch.tensor([8., 8.], requires_grad=True)

def function_parabola(variable):
    return 10 * (variable ** 2).sum()

def make_gradient_step(function, variable):
    function_result = function(variable)
    function_result.backward()
    variable.data = 0.001 * variable.grad # градиентый шаг
    variable.grad.zero_()
    
for i in range(500):
    make_gradient_step(function_parabola, x)

In [5]:
import torch

x = torch.tensor([8., 8.], requires_grad=True)

optimizer = torch.optim.SGD([x], lr=0.001)

def function_parabola(variable):
    return 10 * (variable ** 2).sum()

def make_gradient_step(function, variable):
    function_result = function(variable)
    function_result.backward()
    optimizer.step()
    
    optimizer.zero_grad()
    
for i in range(500):
    make_gradient_step(function_skewed, x)

In [6]:
# Задание 2
import torch

w = torch.tensor([[5., 10.], [1., 2.]], requires_grad=True)
alpha = 0.001
optimizer =  torch.optim.SGD([w], lr=alpha)# put our code here. Do not forget [] inside SGD constructor !!!!

for _ in range(500):
    # it's critical to calculate function inside the loop:
    function = (w + 7).log().log().prod()
    function.backward()
    optimizer.step()
    optimizer.zero_grad()
    # something is missing here!

print(w) # Код для самопроверки

tensor([[4.9900, 9.9948],
        [0.9775, 1.9825]], requires_grad=True)
