In [2]:
import matplotlib.pyplot as plt
import numpy as np

In [26]:
# NUMPY

#1. Пакет numpy - установка и первое знакомство | NumPy уроки

a = np.array([1,2,3,4,5,6,7,8,9])
# array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[1]
# 2
a[ [1,1,1,1,1] ]
# array([2, 2, 2, 2, 2])
a[ [True, False, True, False, True, False, True, False, False] ]
# array([1, 3, 5, 7])
b = a.reshape(3,3)
# array([[1, 2, 3],
#        [4, 5, 6],
#        [7, 8, 9]])
b[1][2]
b[1, 2]
# 6
a.dtype
# dtype('int32')
a = np.array([1, "2", True])
# array(['1', '2', 'True'], dtype='<U11')
a[0] = 234
# array(['234', '2', 'True'], dtype='<U11')

In [50]:
#2. Основные типы данных. Создание массивов функцией array() | NumPy уроки

a = np.array([1,2,3,4], 'float64')
# array([1., 2., 3., 4.])
# np.sctypeDict все типы данных
a = np.array([1,2,3,4], 'uintc')
# array([1, 2, 3, 4], dtype=uint32)
m = np.complex64(10) 
# (10+0j)
m = np.int16(10.5) 
# 10
a = np.array([1, 1000, 5000], 'int8')
# array([   1,  -24, -120], dtype=int8)
a = np.array([1, 1000, 5000])
# np.complex64(a) out: array([1.e+00+0.j, 1.e+03+0.j, 5.e+03+0.j], dtype=complex64)
b = np.complex64(a)
c = np.int32(b)
# ComplexWarning: Casting complex values to real discards the imaginary part
# array([   1, 1000, 5000])
m = np.array( (1,2,3) ) 
# array([1, 2, 3])
m = np.array( "Hello" )
# array('Hello', dtype='<U5') прим. Список из символов
m = np.array([[1, 2], [3, 4], [5, 6]])
#array([[1, 2],
#       [3, 4],
#       [5, 6]])
m = np.array([[1, 2], [3, 4], [5, 6, 7]])
# VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
b = np.array([ [[1,2], [3,4]], [[5,6], [7,8]], [[9, 10], [11,12]] ])
#array([[[ 1,  2],
#        [ 3,  4]],

#       [[ 5,  6],
#        [ 7,  8]],

#       [[ 9, 10],
#        [11, 12]]])
b[0]
#array([[1, 2],
#       [3, 4]])
b[0,0] # equal b[0][0]
# array([1, 2])
b[0,0,0]
# 1

<ipython-input-50-b944b658b7ec>:17: ComplexWarning: Casting complex values to real discards the imaginary part
  c = np.int32(b)
<ipython-input-50-b944b658b7ec>:28: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  m = np.array([[1, 2], [3, 4], [5, 6, 7]])


1

In [94]:
#3. Функции автозаполнения, создания матриц и числовых диапазонов | NumPy уроки

# Функции автозаполнения элементов массива

m = np.array( [0]*10 )
# array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
m = np.array( [x for x in range(10)] )
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
m = np.empty(10) # создание одномерного массива с произвольными числами
#array([1.14073631e+243, 1.20791517e+233, 3.98386102e+252, 6.15864650e+223,
#       1.98930064e+058, 1.44033956e+214, 1.26112228e+180, 1.35710749e+166,
#       2.16769780e+059, 7.37625608e+097])
m = np.empty(10, 'int16')
# array([ 72,   0, 101,   0, 108,   0, 108,   0, 111,   0], dtype=int16)
m = np.empty((3,2), dtype='int16')
#array([[1, 0],
#       [2, 0],
#       [3, 0]], dtype=int16)
m = np.eye(4)
#array([[1., 0., 0., 0.],
#       [0., 1., 0., 0.],
#       [0., 0., 1., 0.],
#       [0., 0., 0., 1.]])
m = np.eye(4,2)
#array([[1., 0.],
#       [0., 1.],
#       [0., 0.],
#       [0., 0.]])
m = np.identity(5)
#array([[1., 0., 0., 0., 0.],
#       [0., 1., 0., 0., 0.],
#       [0., 0., 1., 0., 0.],
#       [0., 0., 0., 1., 0.],
#       [0., 0., 0., 0., 1.]])
m = np.zeros( (2, 3, 4) )
#array([[[0., 0., 0., 0.],
#        [0., 0., 0., 0.],
#        [0., 0., 0., 0.]],

#       [[0., 0., 0., 0.],
#        [0., 0., 0., 0.],
#        [0., 0., 0., 0.]]])
m = np.ones( [4,3], dtype='int8' )
#array([[1, 1, 1],
#       [1, 1, 1],
#       [1, 1, 1],
#       [1, 1, 1]], dtype=int8)
m = np.full((3, 2), -1)
#array([[-1, -1],
#       [-1, -1],
#       [-1, -1]])

# Функции создания матриц

m = np.mat('1 2 3 4') # np.mat('1, 2, 3, 4')
# matrix([[1, 2, 3, 4]])

m = np.mat('1,2; 3 4') # equal np.mat( [(1,2), (3,4)] )
#matrix([[1, 2],
#        [3, 4]])

# np.mat( [(1,2,3), (4,5,6,7)])# ошибка, размерности не совпадают

m = np.diag([1, 2, 3])
#array([[1, 0, 0],
#       [0, 2, 0],
#       [0, 0, 3]])

m = np.diag( [(1,2,3), (4,5,6), (7,8,9)] ) # выделение элементов главной диагонали
# array([1, 5, 9])

m = np.diagflat( [(1,2,3), (4,5,6)] )
#array([[1, 0, 0, 0, 0, 0],
#       [0, 2, 0, 0, 0, 0],
#       [0, 0, 3, 0, 0, 0],
#       [0, 0, 0, 4, 0, 0],
#       [0, 0, 0, 0, 5, 0],
#       [0, 0, 0, 0, 0, 6]])

m = np.tri(4) # 4x4; np.tri(4, 2) 4x2 
#array([[1., 0., 0., 0.],
#       [1., 1., 0., 0.],
 #      [1., 1., 1., 0.],
 #      [1., 1., 1., 1.]])

a = np.array( [(1,2,3), (4,5,6), (7,8,9)] ) # приведение к треугольному виду:
m = np.tril(a) # нижняя треугольная матрица 3х3
#array([[1, 0, 0],
#       [4, 5, 0],
#       [7, 8, 9]])
m = np.triu(a) # верхняя треугольная матрица 3х3
#array([[1, 2, 3],
 #      [0, 5, 6],
 #      [0, 0, 9]])

m = np.tril([1,2,3]) # np.tril([[1,2,3], [4,5,6]])
#array([[1, 0, 0],
#       [1, 2, 0],
#       [1, 2, 3]])

m = np.vander([1,2,3]) # матрица Вандермонда
#array([[1, 1, 1],
#       [4, 2, 1],
#       [9, 3, 1]])

# Функции формирования числовых диапазонов

# аналоги range(), но гибкие и позволяют использование вещественных величин в параметрах
m = np.arange(5) # [0,5) step 1
# array([0, 1, 2, 3, 4])
m = np.arange(2,5) # [2,5) step 1
# array([2, 3, 4])
m = np.arange(1, 5, 0.5) # [1,5) step 0,5
# array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])
m = np.cos(np.arange(0, np.pi, 0.1))

m = np.linspace(0, np.pi, 3) # разбить [0;pi] на 3 отрезка: 0, pi/2, pi; аналоги logspace и geomspace
# array([0.        , 1.57079633, 3.14159265])

# Функции формирования массивов на основе данных

a = np.array( [(1,2), (3,4)] )
b = np.copy(a)

def getRange(x, y):
    return 100*x + y
a = np.fromfunction(getRange, (2, 2)) # ~ np.fromfunction(lambda x, y: x*100+y, (2, 2))
#print(a)
#[[  0.   1.]
 #[100. 101.]]
m = np.fromiter("hello", dtype='U1')
# array(['h', 'e', 'l', 'l', 'o'], dtype='<U1')

m = np.fromstring('2 3 4', dtype='int16', sep=' ') # sep определяет разделитель
# array([2, 3, 4], dtype=int16)

array([2, 3, 4], dtype=int16)

In [112]:
#4 Свойства и представления массивов, создание их копий
#(Один и тот же массив в NumPy может иметь разное представление и математически 
#и программно обрабатываться по разному.)
# Главное понимать, что в NumPy массивы и их представления – это разные понятия.
# псевдопример. shape представляет массив в заданной размерности, reshape возвращает новый массив в заданной размерности

a = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
a.dtype # dtype('float64')
a.dtype = np.int8() # change type and data
a.size # 72 elements
a.dtype = np.float64()
a.size # 9 elements as in up 'a', if float32, then 18 elements
a.itemsize # 8 (bytes) one element
a.size * a.itemsize # 72 (bytes) data memory for massive

# Представления массивов

b = np.ones( (3,4,5) ) # massive of ones 3x4x5
b.ndim # кол-во осей - 3
b.shape # размеры каждой из осей (3, 4, 5)
b.shape = 60 # все 60 элементов вытянтся в строку (изменять так, чтобы не out of range) 
b.shape = (12, 5) # массив 12x5
d = b.T # транспонирование
d.shape # (5, 12), при этом b не изменилась

# Метод view() для создания представления

a = np.array([1,2,3,4,5,6,7,8,9])
b = a # a и b ссылаются на один и тот же массив, бех копирования
a.shape = 3,3 # а и b ссылаются на одну и ту же матрицу в виде 3x3

a = np.array([1,2,3,4,5,6,7,8,9])
b = a.view() # создание нового представления
a.shape = 3,3 # не изменяет массив, на который ссылается b

# Создание копий массивов

a = np.array([1,2,34,5,6,7,8,9])
b = np.array( a ) # создание копии массива, аналогично b = a.copy() 

In [181]:
#5 Изменение формы массивов, добавление и удаление осей

# Изменение размерности массивов

a = np.arange(10)
a.shape = 2,5
# В результате изменится представление массива, на которое ссылается переменная a. Если же требуется 
#создать новое представление массива, сохранив прежнее, то следует воспользоваться методом reshape():
b = a.reshape(10)
b[0] = -1
a.shape = -1, 2 # а 5x2, b не изменилось
b.reshape(-1, 1) # размерность 10x1
# array([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9])
b.reshape(1, -1) # размерность 1x10
# array([[-1,  1,  2,  3,  4,  5,  6,  7,  8,  9]])
b.reshape(-1, 2) # 5x2
#array([[-1,  1],
#       [ 2,  3],
#       [ 4,  5],
#       [ 6,  7],
#       [ 8,  9]])
c = b.ravel() # ссылается на одномерное представление массива
b.shape = -1 # одномерный массив, аналог: .resize()

# Транспонирование матриц и векторов

a = np.array([(1, 2, 3), (1, 4, 9), (1, 8, 27)])
b = a.T
#array([[ 1,  1,  1],
#       [ 2,  4,  8],
#       [ 3,  9, 27]])
b[0][1] = 10
x = np.arange(1, 10)
x.T # array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# В результате ничего не изменилось: вектор как был строкой, так строкой и остался. Почему? Дело в том, 
#что массив x имеет только одну размерность, поэтому здесь нет понятия строк и столбцов. Соответственно, 
#операция транспонирования ни к чему не приводит. Чтобы получить ожидаемый эффект, нужно добавить к массиву 
#еще одну ось, например, так:
x.shape = 1, -1
x.T # 9x1
#array([[1],
#       [2],
 #      [3],
 #      [4],
#       [5],
#       [6],
#       [7],
#       [8],
#       [9]])

# Добавление и удаление осей

x_test = np.arange(32).reshape(8,2,2) # 8x2x2 восемь матриц 2х2
x_test4 = np.expand_dims(x_test, axis=0)
x_test4.shape # (1, 8, 2, 2)
a = np.append(x_test4, x_test4, axis=0)
a.shape # (2, 8, 2, 2)
b = np.delete(a, 0, axis=0) # (1, 8, 2, 2)
b = np.expand_dims(x_test4, axis=-1) # (1, 8, 2, 2, 1)
c = np.squeeze(b) # (8, 2, 2)
c = np.squeeze(b, axis=0) # (8, 2, 2, 1)

# Объект newaxis

a = np.arange(1, 10)
b = a[np.newaxis, :] # добавить ось axis0 (1, 9)
b = a[np.newaxis, :, np.newaxis] # (1, 9, 1)

In [29]:
#6 Объединение и разделение массивов

# Функции hstack и vstack
a = np.array([(1, 2), (3, 4)])
b = np.array([(5, 6), (7, 8)])

m = np.hstack([a, b])
#array([[1, 2, 5, 6],
 #      [3, 4, 7, 8]])
m = np.vstack([a, b])
#array([[1, 2],
#       [3, 4],
#       [5, 6],
#       [7, 8]])
a = np.fromiter(range(18), dtype='int32')
b = np.fromiter(range(18,36), dtype='int32')
a.resize(3,3,2)
b.resize(3,3,2)
c = np.hstack([a, b])
d = np.vstack([a, b])
a = np.fromstring('1 2 3 4', sep=' ')
b = np.fromstring('5 6 7 8', sep=' ')
m = np.vstack([a, b]) # np.vstack([a, b])
m = np.vstack([a, b])
#array([[1., 2., 3., 4.],
 #      [5., 6., 7., 8.]])

# Функции column_stack и row_stack

m = np.column_stack([a, b]) # 4x2
#array([[1., 5.],
#       [2., 6.],
#       [3., 7.],
#       [4., 8.]])
m = np.row_stack([a, b]) # 2x4
#array([[1., 2., 3., 4.],
#       [5., 6., 7., 8.]])

# Функция concatenate

a = np.arange(1, 13) # array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
b = np.arange(13, 26) # array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])
a.resize(3, 3, 2)
#array([[[ 1,  2],
#        [ 3,  4],
#        [ 5,  6]],
#
#       [[ 7,  8],
#        [ 9, 10],
#        [11, 12]],
#
#       [[ 0,  0],
#        [ 0,  0],
#        [ 0,  0]]])
b.resize(3, 3, 2)
#array([[[13, 14],
#        [15, 16],
#        [17, 18]],
#
#       [[19, 20],
#        [21, 22],
#        [23, 24]],
#
#       [[25,  0],
#        [ 0,  0],
#        [ 0,  0]]])
c0 = np.concatenate([a, b], axis=0) # 6x3x2
#array([[[ 1,  2],
#        [ 3,  4],
#        [ 5,  6]],
#
#       [[ 7,  8],
#        [ 9, 10],
#        [11, 12]],
#
#       [[ 0,  0],
#        [ 0,  0],
#        [ 0,  0]],
#
#       [[13, 14],
#        [15, 16],
#        [17, 18]],
#
#       [[19, 20],
#        [21, 22],
#        [23, 24]],
#
#       [[25,  0],
#        [ 0,  0],
#        [ 0,  0]]])
c1 = np.concatenate([a, b], axis=1) # 3x6x2
#array([[[ 1,  2],
#        [ 3,  4],
#        [ 5,  6],
#        [13, 14],
#        [15, 16],
#        [17, 18]],
#
#       [[ 7,  8],
#        [ 9, 10],
#        [11, 12],
#        [19, 20],
#        [21, 22],
#        [23, 24]],
#
#       [[ 0,  0],
#        [ 0,  0],
#        [ 0,  0],
#        [25,  0],
#        [ 0,  0],
#        [ 0,  0]]])

c2 = np.concatenate([a, b], axis=2) # 3x3x4
#array([[[ 1,  2, 13, 14],
#        [ 3,  4, 15, 16],
#        [ 5,  6, 17, 18]],
#
#       [[ 7,  8, 19, 20],
#        [ 9, 10, 21, 22],
#        [11, 12, 23, 24]],
#
#       [[ 0,  0, 25,  0],
#        [ 0,  0,  0,  0],
#        [ 0,  0,  0,  0]]])

# Объекты r_ и c_

m = np.r_[ [1,2,3], 4, 5 ] # array([1, 2, 3, 4, 5])
m = np.r_[1:9, 90, 100] # array([  1,   2,   3,   4,   5,   6,   7,   8,  90, 100])
m = np.r_[ np.array([1,2,3]), np.array([4,5,6]) ] # array([1, 2, 3, 4, 5, 6])
m = np.r_[ [(1,2,3), (4,5,6)], [(7,8,9)] ]
#array([[1, 2, 3],
#       [4, 5, 6],
#       [7, 8, 9]])
m = np.c_[1:5]
#array([[1],
#       [2],
#       [3],
#       [4]])
m = np.c_[ [1,2,3], [4,5,6] ]
#array([[1, 4],
#       [2, 5],
#       [3, 6]])
m = np.c_[ [(1,2,3), (4,5,6)], [[7], [8]] ]
#array([[1, 2, 3, 7],
#       [4, 5, 6, 8]])

# Разделение массивов

a = np.arange(10) # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
m = np.hsplit(a, 2) # разделить на 2 равные части: [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
a.shape = 10, -1
#array([[0],
#       [1],
#       [2],
#       [3],
#       [4],
#       [5],
#       [6],
#       [7],
#       [8],
#       [9]])
m = np.vsplit(a, 2)
#[array([[0],
#        [1],
#        [2],
#        [3],
#        [4]]),
# array([[5],
#        [6],
#        [7],
#        [8],
#        [9]])]
a = np.arange(12)
a.resize(2, 6)
#array([[ 0,  1,  2,  3,  4,  5],
#       [ 6,  7,  8,  9, 10, 11]])
m = np.hsplit(a, 2)
#[array([[0, 1, 2],
#        [6, 7, 8]]),
# array([[ 3,  4,  5],
#        [ 9, 10, 11]])]
m = np.vsplit(a, 2)
# [array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]

# Функция array_split

a = np.arange(18)
a.resize(3,3,2)
#array([[[ 0,  1],
#        [ 2,  3],
#        [ 4,  5]],
#
#       [[ 6,  7],
#        [ 8,  9],
#        [10, 11]],
#
#       [[12, 13],
#        [14, 15],
#        [16, 17]]])

m = np.array_split(a, 2, axis=2)
#[array([[[ 0],
#         [ 2],
#         [ 4]],
# 
#        [[ 6],
#         [ 8],
#         [10]],
# 
#        [[12],
#         [14],
#         [16]]]),
# array([[[ 1],
#         [ 3],
#         [ 5]],
# 
#        [[ 7],
#         [ 9],
#         [11]],
# 
#        [[13],
#         [15],
#         [17]]])]
m = np.array_split(a, 3, axis=0)
#[array([[[0, 1],
#         [2, 3],
#         [4, 5]]]),
# array([[[ 6,  7],
#         [ 8,  9],
#         [10, 11]]]),
# array([[[12, 13],
#         [14, 15],
#         [16, 17]]])]
m = np.array_split(a, 3, axis=1)
#[array([[[ 0,  1]],
# 
#        [[ 6,  7]],
# 
#        [[12, 13]]]),
# array([[[ 2,  3]],
# 
#        [[ 8,  9]],
# 
#        [[14, 15]]]),
# array([[[ 4,  5]],
# 
#        [[10, 11]],
# 
#        [[16, 17]]])]

In [89]:
#7 Индексация, срезы, итерирование массивов

a = np.arange(12) # array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
a[2] # 2
a[-1] # 11
a[0] = 100 # change 0 element
b = a[2:4] # array([2, 3]) прим. b - это представление массива а
b[0] = -100
# a == array([ 100,    1, -100,    3,    4,    5,    6,    7,    8,    9,   10, 11])
a[::-1]
# array([  11,   10,    9,    8,    7,    6,    5,    4,    3, -100,    1,
#        100])
a[1:6:2] # array([1, 3, 5])
a[:4] = [-1, -2, -3, -4] # array([-1, -2, -3, -4,  4,  5,  6,  7,  8,  9, 10, 11])
a[4::2] = np.array([10, 20, 30, 40]) # array([-1, -2, -3, -4, 10,  5, 20,  7, 30,  9, 40, 11])

#for x in a:
    #print(x, sep=' ', end=' ')
    # -1 -2 -3 -4 10 5 20 7 30 9 40 11
    
# Индексация и срезы многомерных массивов

x = np.array([(1, 2, 3), (10, 20, 30), (100, 200, 300)])
#array([[  1,   2,   3],
#       [ 10,  20,  30],
#       [100, 200, 300]])
x[1, 1] # 20
x[-1, -1] # 300
x[0] # array([1, 2, 3]) equal x[0, :]
x[:,1] # array([  2,  20, 200]) столбец посередине в x

#for row in x:
#    for val in row:
#        print(val, end=' ')
#    print()
    #1 2 3 
    #10 20 30 
    #100 200 300

#for val in x.flat:
#    print(val, end=' ')
    # 1 2 3 10 20 30 100 200 300
a = np.arange(1, 82).reshape(3,3,3,3)
#array([[[[ 1,  2,  3],
#         [ 4,  5,  6],
#         [ 7,  8,  9]],
#
#        [[10, 11, 12],
#         [13, 14, 15],
#         [16, 17, 18]],
#
#        [[19, 20, 21],
#         [22, 23, 24],
#         [25, 26, 27]]],
#
#
#       [[[28, 29, 30],
#         [31, 32, 33],
#         [34, 35, 36]],
#
#        [[37, 38, 39],
#         [40, 41, 42],
#         [43, 44, 45]],
#
#        [[46, 47, 48],
#         [49, 50, 51],
#         [52, 53, 54]]],
#
#
#       [[[55, 56, 57],
#         [58, 59, 60],
#         [61, 62, 63]],
#
#        [[64, 65, 66],
#         [67, 68, 69],
#         [70, 71, 72]],
#
#        [[73, 74, 75],
#         [76, 77, 78],
#         [79, 80, 81]]]])
a[1,2,0,1] # 47
a[:, 1, :, :] # matrix 3x3x3
#array([[[10, 11, 12],
#        [13, 14, 15],
#        [16, 17, 18]],
#
#       [[37, 38, 39],
#        [40, 41, 42],
#        [43, 44, 45]],
#
#       [[64, 65, 66],
#        [67, 68, 69],
#        [70, 71, 72]]])
a[0, 0] # ~ a[0, 0, :, :]
#array([[1, 2, 3],
#       [4, 5, 6],
#       [7, 8, 9]])
a[:, :, 1, 1] # 3x3 ~ a[..., 1, 1]
#array([[ 5, 14, 23],
#       [32, 41, 50],
#       [59, 68, 77]])

# Списочная индексация

a = np.arange(1, 9)
a[[0]] # array([1])
b = a[[0]] # b - это копия
b[0] = 100 # array([100])
a[[0, 1, 7, 5]] # array([1, 2, 8, 6])
a[[0,0,1,1,1,2,3,4,5,6,7]] # array([1, 1, 2, 2, 2, 3, 4, 5, 6, 7, 8])
z = np.array([0,0,1,1,1,2])
a[z] # array([1, 1, 2, 2, 2, 3])
bIndx = [True, True, False, False, False, True, False, False]
a[bIndx] # array([1, 2, 6])
a[a > 5] # array([6, 7, 8])
a = np.arange(1, 9) # array([1, 2, 3, 4, 5, 6, 7, 8])
i = np.array([[0, 1], [2, 3]])
a[i]
#array([[1, 2],
#       [3, 4]])
a = np.arange(1, 13).reshape(3, 4)
#array([[ 1,  2,  3,  4],
#       [ 5,  6,  7,  8],
#       [ 9, 10, 11, 12]])
indx = [2, 1, 0]
a[indx]
#array([[ 9, 10, 11, 12],
#       [ 5,  6,  7,  8],
#       [ 1,  2,  3,  4]])
indx = np.array([[1, 0], [2, 1]])
a[indx]
#array([[[ 5,  6,  7,  8],
#        [ 1,  2,  3,  4]],
#
#       [[ 9, 10, 11, 12],
#        [ 5,  6,  7,  8]]])
a[[0, 1], [1, 2]] # array([2, 7])
a[:, [1, 2]]
#array([[ 2,  3],
#       [ 6,  7],
#       [10, 11]])
 #a[[0, 1], 1] # a[[0, 1], 1]

# Изменение массивов через списочную индексацию

a = np.arange(7) # array([0, 1, 2, 3, 4, 5, 6])
a[[0,4,6]] = [-1, -2, -3] # array([-1,  1,  2,  3, -2,  5, -3])
a[[0, 0, 0, 1]] = [1, 2, 3, 100] # array([  3, 100,   2,   3,  -2,   5,  -3])
a[[0, 0, 0]] = a[[0, 0, 0]] + 3 # array([  6, 100,   2,   3,  -2,   5,  -3])
a[[0, 0, 1, 2]] += 1 # array([  7, 101,   3,   3,  -2,   5,  -3])

In [32]:
#8 Базовые математические операции над массивами

lst = [1, 2, 3]
a = np.array([1, 2, 3])
lst*2 # [1, 2, 3, 1, 2, 3]
a*2 # array([2, 4, 6])
[x*2 for x in lst] # [2, 4, 6]
b = np.array([3,4,5])
a - b # array([-2, -2, -2])
a + b # array([4, 6, 8])
b * a # array([ 3,  8, 15])
b / a # array([3.        , 2.        , 1.66666667])
b // a # array([3, 2, 1], dtype=int32)
b ** a # array([  3,  16, 125], dtype=int32)
b % a # array([0, 0, 2], dtype=int32)
b = np.arange(1, 7)
b.resize(2, 3)
#array([[1, 2, 3],
#       [4, 5, 6]])
a + b # Транслирование массивов
#array([[2, 4, 6],
#       [5, 7, 9]])
a = np.arange(1, 19)
a.resize(3,3,2)
#array([[[ 1,  2],
#        [ 3,  4],
#        [ 5,  6]],
#
#       [[ 7,  8],
#        [ 9, 10],
#        [11, 12]],
#
#       [[13, 14],
#        [15, 16],
#        [17, 18]]])
b = np.ones((3, 2))
#array([[1., 1.],
#       [1., 1.],
#       [1., 1.]])
a - b
#array([[[ 0.,  1.],
#        [ 2.,  3.],
#        [ 4.,  5.]],
#
#       [[ 6.,  7.],
#        [ 8.,  9.],
#        [10., 11.]],
#
#       [[12., 13.],
#        [14., 15.],
#        [16., 17.]]])
a*10
#array([[[ 10,  20],
#        [ 30,  40],
#        [ 50,  60]],
#
#       [[ 70,  80],
#        [ 90, 100],
#        [110, 120]],
#
#       [[130, 140],
#        [150, 160],
#        [170, 180]]])
a // b
#array([[[ 1.,  2.],
#        [ 3.,  4.],
#        [ 5.,  6.]],
#
#       [[ 7.,  8.],
#        [ 9., 10.],
#        [11., 12.]],
#
#       [[13., 14.],
#        [15., 16.],
#        [17., 18.]]])
a = np.array([1, 2, 6, 8])
a += 5 # array([ 6,  7, 11, 13])
b = np.ones(4)
b *= a # b = array([ 6.,  7., 11., 13.])

In [66]:
#9 Булевы операции и функции, значения inf и nan

a = np.array([1, 2, 3, 10, 20, 30])
b = np.array([1, 2, 3, 4, 5, 6])
a == b # array([ True,  True,  True, False, False, False])
a >= b # array([ True,  True,  True,  True,  True,  True])
a <= b # array([ True,  True,  True, False, False, False])
a != b # array([False, False, False,  True,  True,  True])

# Функции greater, less, equal

m = np.greater(a, b) # a > b array([False, False, False,  True,  True,  True])
m = np.less(a, b) # a < b array([False, False, False, False, False, False])
m = np.equal(a, b) # array([ True,  True,  True, False, False, False])

# Функции array_equal, all и any

# if(a == b): print("a == b") | out: ERROR
if np.array_equal(a, b): print("a == b")
np.any(a > 5) # True если хотя бы один элемент массива > 5
np.any(a == 5) # False
np.any(a == b) # True, если хотя бы один элемент массива равен другому элементу массива
np.all(a > 5) # False
np.all(a > 0) # True
np.all(a == b) # False

# Значения -inf, inf и nan

a/0 # array([inf, inf, inf, inf, inf, inf])
b = np.array([1, 2, np.inf])
c = b*0 # array([ 0.,  0., nan])
c.sum() # nan

# Функции isnan и isinf

b = np.array([1, 2, np.nan, np.inf, -np.inf])
np.isinf(b) # array([False, False, False  True,  True])
np.isnan(b) # array([False, False,True, False, False])
indx = np.isinf(b)
b[~indx] # ~indx инвертирует булевы значения

# Дополнительные функции: isfinite, iscomplex, isreal

np.isfinite(b) # array([ True,  True, False, False, False])
a = np.array([1+2j, 3-4j, 5])
np.iscomplex(a) # array([ True,  True, False])
np.isreal(a) # array([False, False,  True])

# Функции logical_and, logical_or, logical_not и logical_xor

X = np.array([True, False, True, False])
Y = np.array([True, True, False, False])
np.logical_and(X, Y) # array([ True, False, False, False])
np.logical_or(X, Y) # array([ True,  True,  True, False])
np.logical_not(X) # array([False,  True, False,  True])
np.logical_xor(X, Y) # array([False,  True,  True, False])
a = np.array([1, 0, 2, 0])
b = np.array([3, 4, 0, 0])
np.logical_and(a, b) # array([ True, False, False, False])

<ipython-input-66-9305730e8f56>:29: RuntimeWarning: divide by zero encountered in true_divide
  a/0 # array([inf, inf, inf, inf, inf, inf])
<ipython-input-66-9305730e8f56>:31: RuntimeWarning: invalid value encountered in multiply
  c = b*0 # array([ 0.,  0., nan])


array([ True, False, False, False])

In [132]:
#10 Базовые математические функции

# Функции sum, mean, min и max

a = np.array([1, 2, 3, 10, 20, 30])
a.sum() # 66
a.mean() # 11.0 среднее значение
a.max() # 30
a.min() # 1
a.resize(3, 2)
#array([[ 1,  2],
#       [ 3, 10],
#       [20, 30]])
a.sum() # 66
a.sum(axis=0) # array([24, 42]) СЛОЖЕНИЕ СТОЛБЦОВ
a.sum(axis=1) # array([ 3, 13, 50]) СЛОЖЕНИЕ СТРОК
a.max(axis=0) # array([20, 30])
a.min(axis=1) # array([ 1,  3, 20])

# Базовые математические функции

a = np.array([-1, 1, 5, -44, 32, 2])
np.abs(a) # array([ 1,  1,  5, 44, 32,  2])
np.amax(a) # 32
np.log(a) # array([       nan, 0.        , 1.60943791,        nan, 3.4657359 , 0.69314718])
np.around(0.7) # 1.0
a.resize(2, 3)
#array([[ -1,   1,   5],
#       [-44,  32,   2]])
np.amax(a, axis=0) # array([-1, 32,  5])
np.argmax(a, axis=1) # array([2, 1], dtype=int64)

# Тригонометрические функции

a = np.linspace(0, np.pi, 10)
#array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
#       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])
res1 = np.sin(a)
np.sin(np.pi/3) # 0.8660254037844386
np.cos([0, 1.57, 3.17]) # array([ 1.00000000e+00,  7.96326711e-04, -9.99596538e-01])
res2 = np.cos(a)

# Функции генерации псевдослучайных чисел

np.random.rand() # # вещественное случайное число от 0 до 1
np.random.rand(5) # array([0.95295635, 0.15580665, 0.86423215, 0.08253828, 0.77769382])
np.random.rand(2, 3) # 2x3
#array([[0.64548809, 0.11372955, 0.95477564],
#       [0.12836808, 0.004488  , 0.67073704]])
np.random.randint(10) # генерация целых чисел в диапазоне [0; 10)
np.random.randint(5, 10) # [5;10)
np.random.randint(5, size=4) # array([0, 4, 1, 0])
np.random.randint(1, 10, size=(2, 5))
#array([[6, 6, 1, 6, 3],
#       [9, 4, 2, 4, 6]])
np.random.randn() # нормальная СВ с нулевым средним и единичной дисперсией
np.random.randn(5) # массив из пяти нормальных СВ
np.random.randn(2, 3) # матрица 2x3 из нормальных СВ
np.random.pareto(2.0, size=3) # # распределение Паретто с параметром 2,0
np.random.beta(0.1, 0.3, size=(3, 3)) # # бета-распределение с параметрами 0,1 и 0,3
np.random.seed(13) # # начальное значение генератора случайных чисел
#и все последующие запуски будут давать одну и ту же последовательность чисел, например:
np.random.randint(10, size=10) # array([2, 0, 0, 6, 2, 4, 9, 3, 4, 2])
np.random.randint(10, size=10) # array([6, 5, 9, 4, 2, 0, 3, 5, 3, 6])
np.random.seed(13)
np.random.randint(10, size=10) # array([2, 0, 0, 6, 2, 4, 9, 3, 4, 2])
np.random.randint(10, size=10) # array([6, 5, 9, 4, 2, 0, 3, 5, 3, 6])

# Функции перемешивания элементов массива

a = np.arange(10) # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.random.shuffle(a) # array([8, 7, 9, 6, 3, 4, 0, 2, 1, 5])
np.random.shuffle(a) # array([7, 2, 1, 5, 8, 6, 4, 3, 9, 0])
a = np.arange(1, 10).reshape(3, 3)
np.random.shuffle(a)
#array([[1, 2, 3],
#       [7, 8, 9],
#       [4, 5, 6]])
np.random.permutation(10) # array([0, 9, 4, 6, 3, 2, 7, 5, 1, 8]) realy random

# Функции математической статистики

x = np.array([1, 4, 3, 7, 10, 8, 14, 21, 20, 23])
y = np.array([4, 1, 6, 9, 13, 11, 16, 19, 15, 22])
np.median(x) # 9.0
np.std(y) # среднеквадратичное отклонение 6.359245238233859
np.var(x) # дисперсия 57.29
XY = np.vstack([x, y]) # 2x10
#array([[ 1,  4,  3,  7, 10,  8, 14, 21, 20, 23],
#       [ 4,  1,  6,  9, 13, 11, 16, 19, 15, 22]])
np.corrcoef(XY) # линейный коэфф. корелляции Пирсона
#array([[1.        , 0.93158099],
#       [0.93158099, 1.        ]])
np.cov(XY) # ковариационная матрица
#array([[63.65555556, 49.82222222],
#       [49.82222222, 44.93333333]])
np.correlate(x, y) # array([1736])

<ipython-input-132-11fac91edcd1>:25: RuntimeWarning: invalid value encountered in log
  np.log(a) # array([       nan, 0.        , 1.60943791,        nan, 3.4657359 , 0.69314718])


array([1736])

In [152]:
#11 Произведение матриц и векторов, элементы линейной алгебры

a = np.arange(1, 10).reshape(3, 3)
b = np.arange(10, 19).reshape(3, 3)
a*b
#array([[ 10,  22,  36],
#       [ 52,  70,  90],
#       [112, 136, 162]])

# Матричное умножение

np.dot(a, b) # ~ np.matmul(a, b)
#array([[ 84,  90,  96],
#       [201, 216, 231],
#       [318, 342, 366]])
a = np.arange(1, 10)
b = np.ones(9)
np.inner(a, b) # ~ a @ b внутреннее умножение векторов 45.0
np.outer(a, b)
#array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
#       [2., 2., 2., 2., 2., 2., 2., 2., 2.],
#       [3., 3., 3., 3., 3., 3., 3., 3., 3.],
#       [4., 4., 4., 4., 4., 4., 4., 4., 4.],
#       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
#       [6., 6., 6., 6., 6., 6., 6., 6., 6.],
#       [7., 7., 7., 7., 7., 7., 7., 7., 7.],
#       [8., 8., 8., 8., 8., 8., 8., 8., 8.],
#       [9., 9., 9., 9., 9., 9., 9., 9., 9.]])
a @ b # 45.0
a.resize(3, 3)
b.resize(3, 3)
a @ b
#array([[ 6.,  6.,  6.],
#       [15., 15., 15.],
#       [24., 24., 24.]])

# Умножение вектора на матрицу

a = np.array([1,2,3])
b = np.arange(4,10).reshape(3,2)
np.dot(a, b) # array([40, 46])
a = np.array([1, 2])
np.dot(b, a) # array([14, 20, 26])
a.shape = -1, 1 # 2x1
#array([[1],
#       [2]])
np.dot(b, a)
#array([[14],
#       [20],
#       [26]])

# Элементы линейной алгебры

a = np.array([(1,2,3), (1,4,9), (1,8,27)])
#array([[ 1,  2,  3],
#       [ 1,  4,  9],
#       [ 1,  8, 27]])
np.linalg.matrix_rank(a) # ранг 3
y = np.array([10, 20, 30])
# корни уравнения можно вычислить с помощью функции solve
np.linalg.solve(a, y) # array([-5.        , 10.        , -1.66666667]) 
invA = np.linalg.inv(a) # обратная матрица
invA @ y # вычисление корней array([-5.        , 10.        , -1.66666667])

array([-5.        , 10.        , -1.66666667])

In [174]:
#12 Множества (unique) и операции над ними

#мн-во должно иметь уникальные значения
a = np.array([1, 2, 3, 4, 4, 3, 2 ,1])
setA = np.unique(a) # array([1, 2, 3, 4])
np.unique(a, return_counts=True) # (array([1, 2, 3, 4]), array([2, 2, 2, 2], dtype=int64))
np.unique(a, return_index=True) # (array([1, 2, 3, 4]), array([0, 1, 2, 3], dtype=int64))
np.unique(a, return_inverse=True) # (array([1, 2, 3, 4]), array([0, 1, 2, 3, 3, 2, 1, 0], dtype=int64))
# восстановим массив a
setA, indx = np.unique(a, return_inverse=True)
aa = setA[indx] # array([1, 2, 3, 4, 4, 3, 2, 1])
x = np.array([[0, 1, 1, 2], [0, 1, 1, 2], [9, 1, 1, 2]])
np.unique(x) # array([0, 1, 2, 9])
np.unique(x, axis=0)
#array([[0, 1, 1, 2],
#       [9, 1, 1, 2]])
np.unique(x, axis=1)
#array([[0, 1, 2],
#       [0, 1, 2],
#       [9, 1, 2]])

# Операции над множествами

x = np.array([0, 1, 2, 3])
y = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.in1d(x, y) # array([False,  True,  True,  True]) проверка вхождения x в y
np.random.shuffle(y) # array([4, 1, 2, 8, 5, 7, 6, 3])
np.in1d(x, y) # array([False,  True,  True,  True])

# Пересечение множеств

np.intersect1d(x, y) # array([1, 2, 3])

# Объединение множеств

np.union1d(x, y) # array([0, 1, 2, 3, 4, 5, 6, 7, 8])

# Вычитание множеств

np.setdiff1d(x, y) # array([0])
np.setdiff1d(y, x) # array([4, 5, 6, 7, 8])

# Симметричная разность (XOR)

np.setxor1d(x, y) # array([0, 4, 5, 6, 7, 8])

array([0, 4, 5, 6, 7, 8])

In [184]:
#13 Транслирование массивов

a = np.array([1, 2, 3, 4, 10, 20, 30])
b = np.array([2])
a*b # array([ 2,  4,  6,  8, 20, 40, 60])
a+b # array([ 3,  4,  5,  6, 12, 22, 32])
#В первом случае каждый элемент массива a будет умножен на первый элемент массива b. А во втором случае выполняется аналогичная операция сложения. Но почему это сработало? Например, если мы в массиве b пропишем два элемента:
#
#b = np.array([2, 3])
#и выполним ту же операцию умножения:
#
#a*b # ошибка, размеры не согласованы
#возникнет ошибка. Так почему в первом случае это сработало, а во втором – не сработало? Все дело в особенностях работы алгоритма транслирования массивов пакета NumPy, который следует двум правилам:
#
#Если массивы имеют разное число осей (размерностей), то к массиву с меньшим их числом добавляются новые так, чтобы размерности совпадали. (Причем, добавление всегда происходит с оси axis0).
#Оси с одним элементом расширяются (по числу элементов) так, чтобы соответствующие размерности двух массивов совпадали.
a.ndim # 1
b.ndim # 1; первый пункт выполнен; b для операций с а дополняется двойками [2,2,2,2,2,2,2,2,]
a = np.arange(1, 10).reshape(3, 3)
#array([[1, 2, 3],
#       [4, 5, 6],
#       [7, 8, 9]])
b = np.array([4, 5, 6])
a+b
#array([[ 5,  7,  9],
#       [ 8, 10, 12],
#       [11, 13, 15]])
#С точки зрения математики такая операция невозможна. Но в NumPy она легко вычисляется. Как вы догадались, все дело в механизме транслирования. Согласно первому правилу размерность массива b была увеличена до двух, причем, добавлена именно первая ось – axis0:
# a: 3 x 3
# b: 1 x 3
# А, затем, по второму правилу, число элементов вдоль оси axis0  массива b было доведено до трех
# то есть b это:
#array([4, 5, 6],
#        [4, 5, 6],
#        [4, 5, 6])
a = np.arange(6).reshape(3, 1, 2)
#array([[[0, 1]],
#
#       [[2, 3]],
#
#       [[4, 5]]])
b = np.ones(4).reshape(2, 2)
#array([[1., 1.],
#       [1., 1.]])
a*b # 3x2x2
#array([[[0., 1.],
#        [0., 1.]],
#
#       [[2., 3.],
#        [2., 3.]],
#
#       [[4., 5.],
#        [4., 5.]]])
#Как она была реализована? Смотрите, сначала по первому правилу размерность массива b была доведена до размерности массива a:
#
## a:  3  x 1 x 2
## b: (1) x 2 x 2
#Затем, по второму правилу все оси с одним элементом были расширены до нужного числа элементов. В итоге, были сформированы два массива размерностями:
#
## a:  3  x (2) x 2
## b: (3) x  2  x 2
#После их поэлементного умножения, получаем искомый результат. Как видите, все довольно просто.
#
#Однако, если изменить размерность массива a до 2x3x1:
#
#a = a.reshape(2, 3, 1)
#то при математическом действии с массивом b произойдет ошибка:
#
#a * b # ошибка, размеры не согласованы
#Почему это произошло? Смотрите, по первому правилу размерности массивов стали равны:
#
## a:  2  x 3 x 1
## b: (1) x 2 x 2
#Соответственно вторая ось у массива a содержит 3 элемента, а у массива b – два элемента. Как мы уже знаем, эти размерности не могут быть приведены друг к другу. Отсюда и возникает ошибка при их умножении. Но, если размерность массива b сделать 3x2:
#
#b = np.ones(6).reshape(3, 2)
#то все заработает:
#
#a * b # массив 2x3x2
#Вот так происходит транслирование массивов при поэлементных математических операциях.

# Функция ix_()

a = np.array([1, 2, 3])
b = np.array([4, 5])
c = np.array([7, 8, 9, 10])
#И мы собираемся выполнить вот такое вычисление:
#
#a * b + c # ошибка, размеры не согласованы
#Разумеется, здесь возникнет ошибка, так как число элементов в массивах разное. Но, мы можем привести их к согласованной форме, добавив по две новой оси в каждый из них. Причем, размерности сделаем следующими:
#
## a: 1 x 1 x 3
## b: 1 x 2 x 1
## c: 4 x 1 x 1
#Как вы теперь знаете, с такими массивами можно выполнять любые поэлементные операции. Поменяем размерности:
a.shape = 1, 1, -1
b.shape = 1, -1, 1
c.shape = -1, 1, 1
a * b + c # 4x2x3
#array([[[11, 15, 19],
#        [12, 17, 22]],
#
#       [[12, 16, 20],
#        [13, 18, 23]],
#
#       [[13, 17, 21],
#        [14, 19, 24]],
#
#       [[14, 18, 22],
#        [15, 20, 25]]])
#Фактически, мы здесь получили все возможные варианты перемножений вектора a на числа 4 и 5 и сложений с числами 7, 8, 9 и 10. Для этого было достаточно к одномерным массивам добавить соответствующие оси. Так вот, эту операцию можно автоматизировать с помощью функции ix_(), следующим образом:
a = np.array([1, 2, 3])
b = np.array([4, 5])
c = np.array([7, 8, 9, 10])
an, bn, cn = np.ix_(a, b, c)
an*bn+cn # 3x2x4
#array([[[11, 12, 13, 14],
#        [12, 13, 14, 15]],
#
#       [[15, 16, 17, 18],
#        [17, 18, 19, 20]],
#
#       [[19, 20, 21, 22],
#        [22, 23, 24, 25]]])
#Единственным ограничением этой функции является ее применимость только к одномерным массивам. С многомерными она не работает и приводит к ошибке.

array([[[11, 12, 13, 14],
        [12, 13, 14, 15]],

       [[15, 16, 17, 18],
        [17, 18, 19, 20]],

       [[19, 20, 21, 22],
        [22, 23, 24, 25]]])