In [1]:
pip install pytorch-directml

Note: you may need to restart the kernel to use updated packages.


Reason for being yanked: Deprecated, refer to torch-directml instead


In [2]:
import torch
torch.__version__

'1.8.0a0+b50919b'

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get the Python number within a tensor (works only for one-element tensors)
scalar.item()

7

In [15]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [16]:
vector.ndim

1

In [17]:
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [19]:
MATRIX.ndim

2

In [20]:
MATRIX.shape

torch.Size([2, 2])

In [21]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [22]:
TENSOR.ndim

3

In [24]:
TENSOR.shape # 1 массив, содержащий 3 массива в которых по 3 элемента

torch.Size([1, 3, 3])

In [4]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.6313, 0.1542, 0.1264, 0.8743],
         [0.8348, 0.8586, 0.1828, 0.4512],
         [0.5458, 0.7284, 0.0336, 0.6414]]),
 torch.float32)

In [5]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [6]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [7]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [8]:
# Use torch.arange(), torch.range is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

C:\Users\User\AppData\Local\Temp\ipykernel_13452\2452231750.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
ten_zeros = torch.zeros_like(input=zero_to_ten) # ones_like()
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None,
                              device=None,
                              requires_grad=False)

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [12]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=torch.float16)

float_16_tensor.dtype

torch.float16

In [13]:
# bookmark: go to getting information from tensors

In [3]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f"Device of tensor: {some_tensor.device}") # will default to CPU

tensor([[0.0083, 0.6451, 0.7710, 0.8375],
        [0.0762, 0.0714, 0.7377, 0.8126],
        [0.8388, 0.7149, 0.1554, 0.8525]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device of tensor: cpu


In [4]:
# Manipulating tensors

#Addiction +
#Substraction -
#Multiplication (eleement-wise) *
#Division
#Matrix multiplication

In [16]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [17]:
tensor * 10

tensor([10, 20, 30])

In [18]:
tensor # don't change

tensor([1, 2, 3])

In [19]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [20]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [21]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [22]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

In [23]:
# Elem-wise mul
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [24]:
# torch.matmul() method or @
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [25]:
# e-w mul
# [1*1, 2*2, 3*3]
tensor * tensor

tensor([1, 4, 9])

In [26]:
# matmul
# [1*1 + 2*2 + 3*3]
# MUL 2x3 and 3x2, but not 3x2 and 3x2!
tensor @ tensor

tensor(14)

In [2]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [3]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [4]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [8]:
# The operation work when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([3, 2]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [10]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A ,tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [11]:
# VISUAL MATMUL http://matrixmultiplication.xyz

In [12]:
# bookmark: torch.nn.Linear()

In [1]:
# learn and break, learn and break.

In [5]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=2, out_features=6)

x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward>)

Output shape: torch.Size([3, 6])


In [6]:
# Find min max mean sum etc

In [7]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [8]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print x.mean - this will error
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [10]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [11]:
# Возврат индексов макс или мин значений
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [12]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [13]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [15]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [19]:
tens_bool = tensor.type(torch.bool)
tens_bool

tensor([True, True, True, True, True, True, True, True, True])

In [3]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [4]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [5]:
# Change view (keeps same data as original but changed view)
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [7]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [11]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try dim=1
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [12]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [14]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [16]:
# unsqueeze
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [19]:
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

#Note: Because permuting returns a view (shares the same data as the original),
#the values in the permuted tensor will be the same as the original tensor and 
#if you change the values in the view, it will change the values of the 
#original.

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [20]:
# Indexing tensors

In [2]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [4]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [5]:
#You can also use : to specify "all values in this dimension" and then use 
#a comma (,) to add another dimension.

In [6]:
# Get all values of 0th dim and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [7]:
# Get all values of 0th & 1st dims but only index 1 of 2nd dim
# Получить все значения 0-го dim и 0-го индекса 1-го измерения
x[:, :, 1]

tensor([[2, 5, 8]])

In [21]:
# Get all values of the 0th & 1st dims but only index 1 of 2nd dim
# Получить все значения 0-го и 1-го затемнений, но только индекс 1 2-го 
#измерения
x[:, :, 1]

tensor([[2, 5, 8]])

In [22]:
# Get all values of the 0 dim but only the 1 index value of the 1st and 2nd dim
# Получить все значения 0 dim, но только значение индекса 1 для 1-го и 2-го dim
x[:, 1, 1]

tensor([5])

In [23]:
# Get index 0 of 0th and 1st dim and all values of 2nd dim
# Получить индекс 0 в 0-й и 1-м измерении и все значения 2-го измерения
x[0, 0, :]

tensor([1, 2, 3])

In [1]:
# Автор говорит, что до сих пор путается в индексации и вынужден методом проб и
# ошибок искать правильную индексацию 

In [2]:
# Tensors & numpy

In [2]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [2]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [7]:
tensor = torch.ones(7)# create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy()# create a tensor of ones with dtype=float32
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [8]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [1]:
# Reproducibility (trying to take the random out of random)

In [ ]:
import torch